#!/usr/bin/env python3
"""Thin MCP server exposing Hermes 0.19.0 read-only capabilities to the
Trylo original agent.

Every handler has the same shape: validate input -> call the upstream Hermes
module -> bound the output -> return. No business rules (capacity limits,
FTS queries, threat patterns, frontmatter parsing) are re-implemented here;
those all live in the official Hermes modules imported via ``upstream``.

Transport is stdio. The Claude CLI launches this server through the
``--mcp-config`` generated by ``hermes-capability-manager.js`` and speaks the
Model Context Protocol to it. If this server fails to start, the CLI simply
starts without the trylo-hermes-capabilities tools -- the original agent
keeps working (graceful degradation, the Hermes fusion architecture spec 8.1).
"""

from __future__ import annotations

import json
import logging
import os
import sys
from typing import Optional

from mcp.server.fastmcp import FastMCP

import upstream
from upstream import (
    MemoryStore,
    memory_tool as _memory_tool,
    skill_manage as _skill_manage,
    skills_list as _skills_list,
    skill_view as _skill_view,
    session_search as _session_search,
    write_approval as _wa,
    MEMORY_SCHEMA,
    ok,
    err,
)

logging.basicConfig(level=logging.INFO, format="hermes-capabilities: %(message)s")
logger = logging.getLogger("hermes-capabilities")

mcp = FastMCP("trylo-hermes-capabilities")

# Soft cap on any single tool result so a huge SKILL.md or session dump cannot
# blow up the agent's context. Truncation is signalled in the payload.
MAX_TOOL_CHARS = int(os.environ.get("TRYLO_HERMES_MAX_TOOL_CHARS", "20000"))

# Learning profile: when TRYLO_MCP_PROFILE=learning, only register the three
# Skill-learning tools (skills_list, skill_view, skill_propose). All other
# tools (memory, session_search, learning_pending_list) are NOT registered,
# so the MCP protocol does not even advertise them to the model. This is the
# runtime isolation boundary required by 02_LEARNING_L0_INTEGRATION_REPAIR §7.
_LEARNING_PROFILE = os.environ.get("TRYLO_MCP_PROFILE", "") == "learning"
# 09 §5.2: learning profile exposes a fourth tool — learning_graph_summary
# — for the L0 Skill learning model to use as a safe read-only contract.
# Memory cards / bodies are NEVER exposed; Skill nodes + Skill-to-Skill
# edges + clusters + stats only.
_LEARNING_TOOLS = frozenset({"skills_list", "skill_view", "skill_propose", "learning_graph_summary"})

# 24 §3.D2 / 30 §11.4 D1: HISTORY MCP profile (L4 propose-only). Same as
# learning PLUS `memory_propose` so the L4 miner can generate Memory/Skill
# staged proposals. It explicitly does NOT expose `session_search`
# (retrieval is control-plane, 24 §3.D1) nor `memory_snapshot` (the miner
# never reads Memory body) nor any apply/discard/rollback (phase-1 invariant).
_HISTORY_PROFILE = os.environ.get("TRYLO_MCP_PROFILE", "") == "history"
_HISTORY_TOOLS = frozenset({
    "skills_list", "skill_view", "skill_propose",
    "memory_propose", "learning_graph_summary",
})

# 31 L5 §16 / AUTO_01 §1.1: curation profile (L5 governance). Same 4 tools as
# learning (skills_list/view/propose/learning_graph_summary) — NO memory_propose,
# NO apply/discard/rollback, NO session_search/memory_snapshot. The L5 runner
# only reads graph/usage via curation_adapter and stages proposals via
# skill_propose; it never touches disktore.
_CURATION_PROFILE = os.environ.get("TRYLO_MCP_PROFILE", "") == "curation"
_CURATION_TOOLS = frozenset({
    "skills_list", "skill_view", "skill_propose", "learning_graph_summary",
})


def _register_tool(fn):
    """Conditional @_register_tool wrapper.

    In the learning profile, only tools whose __name__ is in _LEARNING_TOOLS
    are registered with the MCP server. In the history profile, only tools in
    _HISTORY_TOOLS. In the curation profile, only tools in _CURATION_TOOLS.
    All other functions are still defined (so imports don't break) but simply
    not advertised to the model.
    """
    if _LEARNING_PROFILE and fn.__name__ not in _LEARNING_TOOLS:
        return fn
    if _HISTORY_PROFILE and fn.__name__ not in _HISTORY_TOOLS:
        return fn
    if _CURATION_PROFILE and fn.__name__ not in _CURATION_TOOLS:
        return fn
    return mcp.tool()(fn)


def _bounded(text: str, limit: int = MAX_TOOL_CHARS) -> str:
    """Return text unchanged if within limit, else truncated with a notice."""
    if not isinstance(text, str):
        text = str(text)
    if len(text) <= limit:
        return text
    return (
        text[:limit]
        + f"\n...[truncated by trylo-hermes-capabilities, {len(text) - limit} more chars]"
    )


@_register_tool
def memory_snapshot() -> str:
    """Read the persistent memory snapshot (MEMORY + USER profile) as a
    frozen, threat-sanitized reference. Use this to recall durable facts about
    the user and their environment that persist across sessions. Read-only;
    it never modifies memory files. Proposed changes go through a separate
    approval flow.
    """
    try:
        store = MemoryStore()
        store.load_from_disk()
        memory_block = store.format_for_system_prompt("memory") or ""
        user_block = store.format_for_system_prompt("user") or ""
        return _bounded(ok(memory=memory_block, user=user_block))
    except Exception as exc:  # pragma: no cover - surfaced to the agent
        logger.exception("memory_snapshot failed")
        return err(f"memory_snapshot failed: {exc}")


@_register_tool
def skills_list(category: Optional[str] = None) -> str:
    """List available Hermes skills (name, description, category). Read-only.
    Pass ``category`` to filter. Use ``skill_view`` to read a skill's full
    content before applying it.
    """
    try:
        return _bounded(_skills_list(category=category))
    except Exception as exc:  # pragma: no cover
        logger.exception("skills_list failed")
        return err(f"skills_list failed: {exc}")


@_register_tool
def skill_view(name: str, file_path: Optional[str] = None) -> str:
    """Read a Hermes skill's SKILL.md, or a linked file via ``file_path``.
    Read-only. Returns the skill content plus its linked-file manifest.
    """
    if not name or not str(name).strip():
        return err("name is required")
    try:
        return _bounded(_skill_view(name=str(name).strip(), file_path=file_path))
    except Exception as exc:  # pragma: no cover
        logger.exception("skill_view failed")
        return err(f"skill_view failed: {exc}")


@_register_tool
def session_search(
    query: Optional[str] = None,
    limit: int = 3,
    session_id: Optional[str] = None,
    around_message_id: Optional[int] = None,
    window: int = 5,
    sort: Optional[str] = None,
    role_filter: Optional[str] = None,
) -> str:
    """Search past sessions (FTS5, CJK-aware) or scroll/browse one. Read-only.
    Discovery: pass ``query``. Scroll: pass ``session_id`` + ``around_message_id``.
    Browse recent sessions: pass nothing. Mirrors the Hermes session_search
    behaviour exactly.
    """
    try:
        return _bounded(
            _session_search(
                query=query or "",
                limit=limit,
                session_id=session_id,
                around_message_id=around_message_id,
                window=window,
                sort=sort,
                role_filter=role_filter,
            )
        )
    except Exception as exc:  # pragma: no cover
        logger.exception("session_search failed")
        return err(f"session_search failed: {exc}")


@_register_tool
def learning_graph_summary() -> str:
    """Read-only summary of the official Hermes learning graph. The
    Skill L0 model uses this contract to discover related Skills and
    choose between patch / edit / create. Memory card bodies and
    titles are NEVER included — only Skill nodes, Skill-to-Skill
    edges, clusters, and stats. The user/webview never see this
    tool result; only the model in the L0 learning run does.
    """
    try:
        import curation_adapter
        result = curation_adapter.build_summary()
        return _bounded(json.dumps(result, ensure_ascii=False))
    except Exception as exc:  # pragma: no cover
        logger.exception("learning_graph_summary failed")
        return err(f"learning_graph_summary failed: {exc}")


def _enforce_write_gate(subsystem: str):
    """Fail-closed pre-check (R1).

    The official write gate MUST be strictly on before any propose is allowed
    to reach the official write function. If ``config.yaml`` is missing,
    corrupt, or has ``write_approval: false``, this returns an err() JSON
    string and the caller MUST NOT call ``memory_tool`` / ``skill_manage``.
    Returns ``None`` when the gate is on.

    This Python-side check is the real safety boundary - it sits right next to
    the official write functions and is not bypassable by a Node-side config
    race (architecture section 2.2).
    """
    if not _wa.write_approval_enabled(subsystem):
        return err(
            "WRITE_APPROVAL_REQUIRED: "
            f"{subsystem}.write_approval is missing, disabled, or unreadable; "
            "proposal refused to avoid a direct permanent write."
        )
    return None


def _require_staged(result: str) -> str:
    """Defense in depth (R1): after the gate pre-check, the official write
    function must report a STAGED proposal. If it instead reports a successful
    *direct* write (staged missing while success is true), refuse to confirm it
    rather than risk a permanent write. Validation/threat errors (success
    false) pass through unchanged - they did not write."""
    try:
        parsed = json.loads(result)
    except Exception:
        return _bounded(result)
    if isinstance(parsed, dict) and parsed.get("success") and not parsed.get("staged"):
        return err(
            "WRITE_APPROVAL_REQUIRED: proposal did not stage "
            "(write_approval may be off); refusing to confirm a direct write."
        )
    return _bounded(result)


@_register_tool
def memory_propose(
    action: str,
    target: str = "memory",
    content: Optional[str] = None,
    old_text: Optional[str] = None,
    operations: Optional[list] = None,
) -> str:
    """[Memory proposal — description installed at registration time from
    upstream.MEMORY_SCHEMA['description'] + Trylo tail. See server.py _install_memory_propose_description.]"""
    gate_error = _enforce_write_gate("memory")
    if gate_error is not None:
        return gate_error
    try:
        store = MemoryStore()
        store.load_from_disk()
        result = _memory_tool(
            action=action,
            target=target,
            content=content,
            old_text=old_text,
            operations=operations,
            store=store,
        )
        return _require_staged(result)
    except Exception as exc:  # pragma: no cover
        logger.exception("memory_propose failed")
        return err(f"memory_propose failed: {exc}")


# 07 §2 C: the FastMCP @mcp.tool() decorator captures the function
# docstring at decoration time, so the previous post-hoc `__doc__`
# assignment could not change what the agent actually saw. We now
# explicitly re-register memory_propose with a description built from
# the upstream MEMORY_SCHEMA['description'] body + a Trylo tail. This
# guarantees the registered MCP tool description equals the official
# Hermes semantics, byte-for-byte, with the Trylo short tail appended.
_TRYLO_MEMORY_TAIL = """
\n\nTrylo-specific additions (appended below the upstream body):
  - The call only stages a Hermes pending proposal; nothing is written
    to MEMORY.md/USER.md until the user explicitly approves it in the
    Trylo UI (the official write_approval gate).
  - Produce at most one coherent Memory pending per turn. For multiple
    operations use the official batch `operations` argument.
  - Do NOT claim the memory was saved — it is pending user approval.
  - Do NOT propose secrets, credentials, API keys, or short-term task
    progress that session_search could recover.
  - Reusable procedure / templates / scripts go to Skill, not Memory.
"""


def _install_memory_propose_description():
    """Build the full memory_propose description from
    upstream.MEMORY_SCHEMA['description'] and register it BEFORE
    FastMCP has a chance to capture the (placeholder) docstring.

    Strategy:
      1. Remove memory_propose from the FastMCP tool manager (it was
         registered with the placeholder docstring by @_register_tool).
      2. Mutate memory_propose.__doc__ to the real description.
      3. Re-register it via mcp.add_tool with the description parameter
         so the registered tool carries the upstream body.

    This is the only place the tool description is installed. Smoke
    tests can read it back via mcp._tool_manager.get_tool('memory_propose').description.
    """
    try:
        upstream_body = str(MEMORY_SCHEMA.get("description") or "").strip()
    except Exception as exc:  # pragma: no cover - fail closed
        logger.warning("failed to read MEMORY_SCHEMA: %s", exc)
        return
    if not upstream_body:
        logger.warning("MEMORY_SCHEMA['description'] is empty; keeping placeholder docstring")
        return

    full_description = upstream_body + _TRYLO_MEMORY_TAIL
    memory_propose.__doc__ = full_description

    # In learning / curation profiles, memory_propose must not be registered at
    # all. _register_tool already returned the function un-decorated in those
    # cases, so mcp._tool_manager does not have it. Skip the re-register.
    if _LEARNING_PROFILE or _CURATION_PROFILE:
        return

    try:
        tool_manager = getattr(mcp, "_tool_manager", None)
        if tool_manager is not None and hasattr(tool_manager, "remove_tool"):
            try:
                tool_manager.remove_tool("memory_propose")
            except Exception:
                pass
    except Exception as exc:  # pragma: no cover
        logger.warning("failed to remove old memory_propose registration: %s", exc)

    try:
        mcp.add_tool(
            memory_propose,
            name="memory_propose",
            description=full_description,
        )
    except Exception as exc:  # pragma: no cover
        logger.warning("failed to re-register memory_propose with upstream description: %s", exc)


_install_memory_propose_description()


@_register_tool
def skill_propose(
    action: str,
    name: str,
    content: Optional[str] = None,
    category: Optional[str] = None,
    file_path: Optional[str] = None,
    file_content: Optional[str] = None,
    old_string: Optional[str] = None,
    new_string: Optional[str] = None,
    replace_all: bool = False,
) -> str:
    """Propose a skill create/edit/patch/write_file/remove_file/delete. STAGED
    for human approval - not written until the user approves in the Trylo UI.
    Do not assume the skill exists until it has been approved.
    """
    gate_error = _enforce_write_gate("skills")
    if gate_error is not None:
        return gate_error
    try:
        result = _skill_manage(
            action=action,
            name=name,
            content=content,
            category=category,
            file_path=file_path,
            file_content=file_content,
            old_string=old_string,
            new_string=new_string,
            replace_all=replace_all,
        )
        return _require_staged(result)
    except Exception as exc:  # pragma: no cover
        logger.exception("skill_propose failed")
        return err(f"skill_propose failed: {exc}")


@_register_tool
def learning_pending_list() -> str:
    """List pending memory/skill proposals awaiting the user's approval.
    Read-only. Use this to see which changes you proposed are still waiting
    for a human decision. Approve/reject happens only in the Trylo UI.
    """
    try:
        out = []
        for sub in ("memory", "skills"):
            for r in _wa.list_pending(sub):
                out.append(
                    {
                        "id": r.get("id"),
                        "subsystem": r.get("subsystem") or sub,
                        "action": r.get("action"),
                        "summary": r.get("summary"),
                        "origin": r.get("origin"),
                        "created_at": r.get("created_at"),
                    }
                )
        return _bounded(ok(pending=out, count=len(out)))
    except Exception as exc:  # pragma: no cover
        logger.exception("learning_pending_list failed")
        return err(f"learning_pending_list failed: {exc}")


def main() -> None:
    # R6: fail-closed on version mismatch. Do not start a service exposing
    # write tools when the pinned Hermes version is wrong - upstream API drift
    # could break write/staging/security semantics. The CLI then starts without
    # trylo-hermes-capabilities and the original Trylo agent runs unchanged.
    vcheck = json.loads(upstream.require_version())
    if not vcheck.get("success"):
        sys.stderr.write(
            f"hermes-capabilities: refusing to start: {vcheck.get('error')}\n"
        )
        sys.exit(1)
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
