// Trylo Desktop — Code permission registry (CLI --permission-prompt-tool
// stdio, migration spec §6.4 Code path).
//
// Owns the pending can_use_tool requests across every Code CLI process
// and answers them by writing a control_response line to the owning
// process's stdin. Request ids are generated by each CLI process and are
// globally unique here, so dual-workspace routing is by-construction
// correct (architecture doc §5.4-3): the decision always travels back to
// the exact request it belongs to.
//
// PR-2 (tool-extension spec §6 / §12.2): when a risk classifier is wired,
// every incoming control_request is classified BEFORE it is projected.
//   auto_allow → answered immediately on stdin, no UI;
//   deny       → answered immediately with a machine-readable reason;
//   prompt     → registered as pending (with the classifier's safe
//                preview) so the ApprovalCard is the decision surface.
// Tools the classifier does not manage (built-ins, the user's own MCP
// servers) keep the legacy register-and-wait behaviour. Classification is
// synchronous and pure, so the stdout path stays race-free; only the
// auto-response write is async, and a FAILED write falls back to a human
// decision instead of dropping the request.
//
// Failure policy: an unknown/expired requestId responds false — the
// caller (ApprovalService) records it in diagnostics; we never guess.

import type { ControlFrame } from '../host-adapter/control-protocol';
import { buildControlResponse } from '../host-adapter/control-protocol';
import type { PermissionLevel } from '../permission/permission-policy';
import type { ApprovalPreview } from '../approval/approval-preview';
import type { SafeAudit, ToolLeaseGrant, ToolRiskRoute, ToolRiskRouter } from '../tooling/tool-risk-classifier';

export interface CodePermissionRequest {
  readonly requestId: string;
  readonly processId: string;
  readonly projectKey: string;
  readonly conversationId: string;
  readonly toolName: string;
  readonly input: Record<string, unknown>;
  readonly title?: string;
  readonly at: number;
  /** PR-2: the classifier's safe preview for prompt decisions. Rendered by
   *  the ApprovalCard; carries paths only, never raw content. */
  readonly preview?: ApprovalPreview;
  /** PR-2: the classifier's risk label for prompt decisions. */
  readonly risk?: 'external' | 'sensitive' | 'destructive';
  /** PR-3 (§6.5): lease the user grants by approving this request. The
   *  registry records it ONLY on an explicit approval — the model cannot
   *  create or extend a lease. */
  readonly lease?: ToolLeaseGrant;
}

export interface CodePermissionScope {
  readonly processId: string;
  readonly projectKey: string;
  readonly conversationId: string;
  /**
   * PR-2 (§6.2): the run context the classifier needs. When either is
   * missing (a scope the classifier cannot evaluate), the request skips
   * classification and takes the default human-approval path — never a
   * guess.
   */
  readonly projectRoot?: string;
  readonly permissionLevel?: PermissionLevel;
  readonly profileId?: string;
  /** Package ids the run's Profile activated (§4.3 explicit composition). */
  readonly managedPackageIds?: readonly string[];
}

/** One audit entry: the classifier's SafeAudit plus the requestId it
 *  decided. Nothing here carries raw tool input. */
export interface CodePermissionAuditEntry extends SafeAudit {
  readonly requestId: string;
}

export interface CodePermissionRegistryOptions {
  /** Called on every visibility change (register / cancel / respond /
   *  clear). The supervisor maps this to its version bump. */
  readonly onChange: () => void;
  /** Stdin write. Defaults to the host adapter's process.send.
   *  Injected for tests. */
  readonly send?: (processId: string, line: string) => Promise<boolean>;
  /** PR-2: host risk classifier consulted before projection. */
  readonly riskClassifier?: ToolRiskRouter | null;
  /** PR-3 (§6.5): records a lease granted by an explicit user approval
   *  (e.g. a first navigation to a new origin). The callback receives the
   *  grant the classifier proposed; the store is shared with the
   *  classifier so later in-origin calls may auto-allow until expiry. */
  readonly onLeaseGrant?: (grant: ToolLeaseGrant) => void;
}

function defaultSend(processId: string, line: string): Promise<boolean> {
  // Lazy import keeps this module constructible in vitest without the
  // Tauri shell; the production path resolves hostAdapter normally.
  return import('../host-adapter/index')
    .then((mod) => mod.hostAdapter.process.send(processId, line))
    .then(() => true)
    .catch(() => false);
}

/** Audits kept in memory for diagnostics; bounded so a runaway loop cannot
 *  grow it unbounded. */
const AUDIT_LIMIT = 64;

export class CodePermissionRegistry {
  private readonly pending = new Map<string, CodePermissionRequest>();
  private readonly onChange: () => void;
  private readonly send: (processId: string, line: string) => Promise<boolean>;
  private readonly riskClassifier: ToolRiskRouter | null;
  private readonly onLeaseGrant: ((grant: ToolLeaseGrant) => void) | null;
  private readonly audits: CodePermissionAuditEntry[] = [];

  constructor(options: CodePermissionRegistryOptions) {
    this.onChange = options.onChange;
    this.send = options.send ?? defaultSend;
    this.riskClassifier = options.riskClassifier ?? null;
    this.onLeaseGrant = options.onLeaseGrant ?? null;
  }

  /** Route a control frame from one process's stdout stream. */
  handleControlFrame(frame: ControlFrame, scope: CodePermissionScope): void {
    if (frame.kind === 'cancel') {
      if (this.pending.delete(frame.requestId)) this.notify();
      return;
    }
    if (this.pending.has(frame.requestId)) return;

    const route = this.classifyFrame(frame, scope);
    if (route) {
      this.recordAudit(frame.requestId, route);
      if (route.behavior === 'auto_allow' || route.behavior === 'deny') {
        // Fire-and-forget: the CLI blocks on the response; a failed write
        // degrades to a pending human decision inside autoRespond.
        void this.autoRespond(frame, scope, route);
        return;
      }
      this.pending.set(frame.requestId, {
        requestId: frame.requestId,
        processId: scope.processId,
        projectKey: scope.projectKey,
        conversationId: scope.conversationId,
        toolName: frame.toolName,
        input: frame.input,
        ...(frame.title ? { title: frame.title } : {}),
        preview: route.preview,
        risk: route.risk,
        ...(route.lease ? { lease: route.lease } : {}),
        at: Date.now(),
      });
      this.notify();
      return;
    }

    this.pending.set(frame.requestId, {
      requestId: frame.requestId,
      processId: scope.processId,
      projectKey: scope.projectKey,
      conversationId: scope.conversationId,
      toolName: frame.toolName,
      input: frame.input,
      ...(frame.title ? { title: frame.title } : {}),
      at: Date.now(),
    });
    this.notify();
  }

  /** Drop every pending request owned by a process (exit / stop /
   *  dispose path). */
  clearProcess(processId: string): void {
    let changed = false;
    for (const [id, request] of this.pending) {
      if (request.processId === processId) {
        this.pending.delete(id);
        changed = true;
      }
    }
    if (changed) this.notify();
  }

  /** Snapshot of pending requests (newest last). */
  list(): readonly CodePermissionRequest[] {
    return [...this.pending.values()];
  }

  /** PR-2: recent classifier decisions (auto and deny included), oldest
   *  first, bounded. Safe to surface in diagnostics. */
  recentAudits(): readonly CodePermissionAuditEntry[] {
    return [...this.audits];
  }

  /** Answer one pending request. Resolves false when the id is unknown
   *  or the stdin write failed (the entry is kept on write failure so a
   *  retry is possible). An approval of a lease-carrying request (PR-3
   *  §6.5) records the grant BEFORE the stdin write so the lease exists
   *  even if the write races the next control frame. */
  async respond(requestId: string, allow: boolean): Promise<boolean> {
    const request = this.pending.get(requestId);
    if (!request) return false;
    if (allow && request.lease) {
      try {
        this.onLeaseGrant?.(request.lease);
      } catch {
        /* a broken lease sink must never block the approval */
      }
    }
    const sent = await this.send(request.processId, buildControlResponse(requestId, allow, request.input));
    if (!sent) return false;
    this.pending.delete(requestId);
    this.notify();
    return true;
  }

  /** Classify one frame, or null when the default path must apply
   *  (no classifier, unmanaged tool, or an un-evaluable scope). */
  private classifyFrame(
    frame: Extract<ControlFrame, { kind: 'permission' }>,
    scope: CodePermissionScope,
  ): Exclude<ToolRiskRoute, { behavior: 'unmanaged' }> | null {
    if (!this.riskClassifier) return null;
    if (!scope.projectRoot || !scope.permissionLevel) return null;
    try {
      const route = this.riskClassifier.classify({
        toolName: frame.toolName,
        input: frame.input,
        permissionLevel: scope.permissionLevel,
        projectRoot: scope.projectRoot,
        conversationId: scope.conversationId,
        profileId: scope.profileId ?? '',
        ...(scope.managedPackageIds !== undefined
          ? { managedPackageIds: scope.managedPackageIds }
          : {}),
      });
      return route.behavior === 'unmanaged' ? null : route;
    } catch {
      // A classifier crash must not break the approval path — route to a
      // human instead of guessing (spec §6.2 fail-closed, not fail-silent).
      return null;
    }
  }

  private recordAudit(requestId: string, route: Exclude<ToolRiskRoute, { behavior: 'unmanaged' }>): void {
    this.audits.push({ requestId, ...route.audit });
    if (this.audits.length > AUDIT_LIMIT) this.audits.splice(0, this.audits.length - AUDIT_LIMIT);
  }

  /** Answer a classified request without ever projecting it. A failed
   *  stdin write registers the request as pending so a human can still
   *  decide — the CLI keeps waiting either way. */
  private async autoRespond(
    frame: Extract<ControlFrame, { kind: 'permission' }>,
    scope: CodePermissionScope,
    route: Extract<ToolRiskRoute, { behavior: 'auto_allow' | 'deny' }>,
  ): Promise<void> {
    const allow = route.behavior === 'auto_allow';
    const line = buildControlResponse(
      frame.requestId,
      allow,
      frame.input,
      route.behavior === 'deny' ? route.userMessage : undefined,
    );
    let sent = false;
    try {
      sent = await this.send(scope.processId, line);
    } catch {
      sent = false;
    }
    if (sent) return;
    if (this.pending.has(frame.requestId)) return;
    this.pending.set(frame.requestId, {
      requestId: frame.requestId,
      processId: scope.processId,
      projectKey: scope.projectKey,
      conversationId: scope.conversationId,
      toolName: frame.toolName,
      input: frame.input,
      ...(frame.title ? { title: frame.title } : {}),
      at: Date.now(),
    });
    this.notify();
  }

  private notify(): void {
    this.onChange();
  }
}
