// Trylo Desktop — CodeRunController.
//
// v1.16.6 (M4-A runtime ownership, spec §5.1/§5.2): owns the FULL
// Code run lifecycle for ONE conversation. There is no module-level
// `activeRunGeneration` / `activeHostProcessId` anymore — each
// controller carries its own generation and process handle, so:
//
//   - starting a run in conversation A never silences a concurrent
//     run in conversation B;
//   - stop() targets THIS controller's child, not "the global
//     active process";
//   - a child that dies on its own (process.exited) clears this
//     controller's binding instead of leaving a fake-lively entry;
//   - the WARM path (reuse the same idle CLI for the next turn)
//     keeps that process's stdout flowing — the generation guard
//     only detaches a process when it is superseded by a new
//     spawn, a stop, or an exit, NOT when a new turn reuses it.
//
// The controller is framework-agnostic: no React. It notifies a
// single `onChange` callback (the supervisor) on any visible-state
// change so the renderer can re-read the ViewState.

import type { LoopEvent } from '../host-adapter/loop-events';
import type { ProcessExitInfo } from '../host-adapter/process-service';
import {
  sendControlLineToProcess,
  sendPromptToProcess,
  startTrylo,
  startTryloPrewarm,
  stopTryloProcess,
} from '../host-adapter/trylo-runner';
import { buildStopTaskRequest } from '../host-adapter/control-protocol';
import type { ChatMessage } from '../components/chat/types';
import type { CodeRunBindingState, CodeRunViewState, SettingsForCodeRun } from './runtime-types';
import type { RuntimeResultScope } from '../results/result-scope';
import type { CodeRunLifecycleObserver, CodeRunOutcome } from './code-run-lifecycle';
import type { CodePermissionRegistry, CodePermissionRequest } from './code-permission-registry';
import type { CodeDiagnosticsBuffer } from '../diagnostics/code-diagnostics-buffer';
import type { PermissionLevel } from '../permission/permission-policy';
import type { ResolvedToolRuntime, ToolSurface } from '../tooling/types';
import { fingerprintForRun } from '../tooling/runtime-fingerprint';
import { spawnEnvForTeamAccess } from '../tooling/team-surface-env';
import { observeToolProtocol, protocolDriftReasonCode } from '../tooling/tool-protocol-observer';

let runSeq = 0;

/** Baseline capture budget (spec §7.2 / §14): a slow Git snapshot never
 *  blocks the run from starting. */
const BASELINE_TIMEOUT_MS = 3000;

export interface CodeRunControllerOptions {
  readonly projectKey: string;
  readonly conversationId: string;
  /** Called whenever the visible ViewState changes. */
  readonly onChange: () => void;
  /** C-Edge P2-5: structured diagnostic event sink. Optional — when
   *  omitted, the controller still runs but produces no diagnostics.
   *  The buffer is owned at the App level (one per app instance) and
   *  is shared across every controller. */
  readonly diagnostics?: CodeDiagnosticsBuffer | null;
  /** §6.4 (Code path): shared pending-permission registry. When wired,
   *  control_request frames from this controller's CLI surface as pending
   *  permissions and are answerable by requestId. Optional — without it,
   *  control frames are dropped (chat/plan mode runs would stall on
   *  approval with no answer path). */
  readonly permissions?: CodePermissionRegistry | null;
}

export interface CodeRunRequest {
  readonly prompt: string;
  readonly settings: SettingsForCodeRun;
  readonly codeMode: 'plan' | 'agent' | 'chat';
  /** P2 (spec §4.4 / §5): the resolved UI permission level for THIS
   *  run, snapshotted by `App.onSend`. The runtime does NOT re-read
   *  it from a global ref; a mid-run picker change must not leak
   *  into the running CLI. */
  readonly permissionLevel: PermissionLevel;
  /** Recovery-only history passed when we must SPAWN (a live
   *  idle process is reused without replaying it). */
  readonly priorMessages: readonly ChatMessage[];
  /** Applied to the ORIGINAL conversation even if the user has
   *  since navigated away (background write-back). */
  readonly onEvents: (events: readonly LoopEvent[]) => void;
  /** M4-C5 (P1-3): fired exactly once per run with the path taken
   *  (warm = reused an idle CLI or adopted a prewarm; cold = a fresh
   *  spawn). Lets App drive RunTelemetry's cold/warm mark. Optional. */
  readonly onRuntimeAcquired?: (info: { warm: boolean }) => void;
  /** P2-1 (spec §7.2): the originating user-message id, generated by App
   *  before the user message is created. The controller passes it into the
   *  result scope; it is NOT a Run primary-key substitute. */
  readonly turnId?: string;
  /** P2-1 (spec §7.2): optional result lifecycle observer. When set, the
   *  controller awaits `onRunStarted` (bounded) before writing the prompt,
   *  forwards structured events via `onEvents`, and fires `onRunTerminal`
   *  exactly once per runId on loop_end / session_end / process exit /
   *  cancel. Result projection failures never block the Agent run. */
  readonly lifecycleObserver?: CodeRunLifecycleObserver;
  /** Hermes MCP args for THIS run (migration spec §7.2 / §7.3). Empty for a
   *  plain run — the learning profile is per-run, never a global default.
   *  A live warm/prewarm process is only reused when its argv matches, so a
   *  learning-capable run can never silently inherit a plain CLI. */
  readonly extraCliArgs?: readonly string[];
  /**
   * The composed Tool Profile for THIS run (tool-extension spec §4.2 / §9).
   *
   * `null` (or omitted) means "no tool plane answer" and is a VALID state:
   * the run degrades to `extraCliArgs` and its fingerprint falls back to the
   * legacy argv key, so a plain Code run keeps byte-identical warm/prewarm
   * behaviour. Two processes may be shared only when the FULL runtime
   * contract matches — model, host, permission level, system prompt, Profile
   * and MCP config — not merely the injected argv (spec §1.4).
   */
  readonly toolRuntime?: ResolvedToolRuntime | null;
  /**
   * §4.2: which surface this run belongs to. Used to ASK for a Profile when
   * `toolRuntime` was left undecided, and to inject TRYLO_TEAM_SURFACE=work
   * even when the Profile is missing so Work seats cannot degrade to Code.
   */
  readonly surface?: ToolSurface;
  readonly requestedProfileId?: string;
  /** Team Access (PR-7): this run's Governor decided spawn_team and the
   *  gate passed. Adds TRYLO_TEAM_MODE to the spawn env so the Code
   *  surface lists the five seats; changes the fingerprint so a warm
   *  stay_solo CLI is never silently reused (spec §14.5). */
  readonly teamMode?: boolean;
}

/** Profile env plus TRYLO_TEAM_SURFACE for Work, even when the Profile is missing.
 *  teamMode adds TRYLO_TEAM_MODE for Code spawn_team runs (never on Work). */
function effectiveSpawnEnv(
  surface: ToolSurface | undefined,
  runtime: ResolvedToolRuntime | null | undefined,
  teamMode?: boolean,
): Readonly<Record<string, string>> {
  return spawnEnvForTeamAccess(surface, teamMode === true, runtime?.spawnEnv);
}

/** Build the full runtime identity of a run (spec §9). */
function runFingerprint(request: Pick<CodeRunRequest, 'settings' | 'permissionLevel' | 'extraCliArgs' | 'toolRuntime' | 'surface' | 'teamMode'>): string {
  const s = request.settings;
  const runtime = request.toolRuntime ?? null;
  return fingerprintForRun({
    cliPath: s.cliPath,
    cwd: s.cwd,
    apiKey: s.apiKey,
    apiHost: s.apiHost,
    apiModel: s.apiModel,
    apiFormat: s.apiFormat,
    apiKeyHeader: s.apiKeyHeader,
    apiKeyPrefix: s.apiKeyPrefix,
    extraHeadersText: s.extraHeadersText,
    systemPrompt: s.systemPrompt,
    permissionLevel: request.permissionLevel,
    // The EFFECTIVE argv: when a Profile was resolved the runner sends the
    // Profile's flags, so the identity must be computed from those — using
    // the raw request args here would mint a different fingerprint for the
    // same actual spawn (the prewarm/run adoption contract would break).
    extraCliArgs: runtime ? [...runtime.cliArgs] : (request.extraCliArgs ?? []),
    toolRuntime: runtime,
    spawnEnv: effectiveSpawnEnv(request.surface, runtime, request.teamMode),
  });
}

export class CodeRunController {
  private readonly projectKey: string;
  private readonly conversationId: string;
  private readonly onChange: () => void;
  /** Optional. When wired, every visible lifecycle transition emits
   *  a hashed event into the buffer. The buffer is the only place
   *  production-mode Code diagnostics live; it never depends on
   *  `RUN_TELEMETRY_DEBUG` or `console.log`. */
  private readonly diagnostics: CodeDiagnosticsBuffer | null;

  /**
   * Detaches superseded processes. Bumped on a NEW spawn, a stop,
   * or a process exit — NOT on warm reuse of the same process. A
   * spawn's stdout handler checks `snapshot === this.generation`
   * so output that belongs to a replaced / stopped process is
   * dropped, while output from the current process (including
   * later turns reusing it) keeps flowing.
   */
  private generation = 0;
  private processId: string | null = null;
  private pid: number | null = null;
  private bindingState: CodeRunBindingState = 'idle';
  private error = false;
  private runId: string | null = null;
  private startedAt = 0;
  /** True while a user turn expects model output. Cleared on
   *  loop_end; if process.exited arrives while busy it is a
   *  crash (error). */
  private busy = false;
  /** P2-1: the result scope for the CURRENT in-flight run. Set at the top
   *  of `run()`, cleared by the exactly-once terminal guard so a late entry
   *  never re-fires. Captured eagerly so a later runId=null (cleanup) can
   *  never orphan the terminal notification. */
  private resultScope: RuntimeResultScope | null = null;
  private lifecycleObserver: CodeRunLifecycleObserver | null = null;
  private readonly permissions: CodePermissionRegistry | null;

  // M4-C1 prewarm: an idle CLI spawned ahead of the first send so
  // cold-start (Node loading the ~50.8 MiB single-file bundle) is
  // OUT of the first-turn critical path. The controller spawns it,
  // records the structured `session_start` gate for telemetry, and a
  // user turn ADOPTS the process as soon as its stdin handle exists.
  // `turnSink` is the conversation-scoped event sink
  // the adopted process routes its turn output through.
  private prewarming = false;
  private prewarmProcessId: string | null = null;
  private prewarmReady = false;
  private prewarmSpawnedAt = 0;
  private lastIdleAt = 0;
  /** Invalidates callbacks from a prewarm that was adopted, superseded,
   *  stopped, or completed after a real run had already started. */
  private prewarmAttempt = 0;
  private turnSink: ((events: readonly LoopEvent[]) => void) | null = null;
  /** The FULL runtime identity of the currently owned process (spec §9).
   *  Null until a spawn lands. A run may reuse this process only when its
   *  own fingerprint is byte-identical — argv alone is not enough, because
   *  model / host / permission level / system prompt / MCP config are all
   *  fixed at spawn time too. */
  private ownedFingerprint: string | null = null;
  /** The runtime identity a prewarmed process was spawned with. */
  private prewarmFingerprint: string | null = null;

  constructor(options: CodeRunControllerOptions) {
    this.projectKey = options.projectKey;
    this.conversationId = options.conversationId;
    this.onChange = options.onChange;
    this.diagnostics = options.diagnostics ?? null;
    this.permissions = options.permissions ?? null;
  }

  /** Stable registry key for this conversation's controller. */
  get key(): string {
    return `${this.projectKey}::${this.conversationId}`;
  }

  getViewState(): CodeRunViewState {
    const starting = this.bindingState === 'spawning';
    const running = this.bindingState === 'busy' || starting;
    return {
      running,
      error: this.error,
      activeProcessId: this.processId,
      sendable: !running,
      bindingState: this.bindingState,
      runId: this.runId,
      pid: this.pid,
    };
  }

  /** A run in flight (for the Activity Center). */
  getActiveRun(): { projectKey: string; conversationId: string; runId: string; startedAt: number; bindingState: CodeRunBindingState } | null {
    if (!this.runId || this.bindingState === 'idle' || this.bindingState === 'exited') {
      return null;
    }
    return {
      projectKey: this.projectKey,
      conversationId: this.conversationId,
      runId: this.runId,
      startedAt: this.startedAt,
      bindingState: this.bindingState,
    };
  }

  /** Pending permission requests owned by THIS conversation's CLI
   *  (§6.4; used by the companion projection / ApprovalService). */
  pendingPermissions(): readonly CodePermissionRequest[] {
    if (!this.permissions) return [];
    return this.permissions.list().filter(
      (request) => request.projectKey === this.projectKey && request.conversationId === this.conversationId,
    );
  }

  /**
   * Drive one user turn on this conversation. Reuses a live idle
   * CLI when one exists; otherwise spawns. Resolves once the prompt
   * is accepted — it does not await the full model loop (that
   * streams via `request.onEvents`). If this controller is
   * superseded while a spawn is in flight, the spawn is cancelled
   * and this resolves quietly.
   */
  /** One-line helper: emit a diagnostic event if a buffer is wired.
   *  Run id is read from the in-flight `runId` so the transition is
   *  always traceable, even when the event fires from a path that
   *  ran without a turn context (e.g. prewarm adoption). */
  private diag(
    type: import('../diagnostics/code-diagnostics-buffer').DiagEventType,
    extras: {
      readonly latencyMs?: number;
      readonly reasonCode?: string;
      readonly exitCode?: number;
      readonly signal?: number;
    } = {},
  ): void {
    const buf = this.diagnostics;
    if (!buf) return;
    const runId = this.runId ?? `prewarm-${this.conversationId}`;
    buf.push({
      type,
      runId,
      projectKey: this.projectKey,
      conversationId: this.conversationId,
      ...extras,
    });
  }

  /**
   * PR-2 (§3 / §4.4): compare the tool list the CLI reported at init against
   * the run Profile's expectedTools. Drift lands in run diagnostics — tool
   * names only, never paths or input. A package whose manifest asserts
   * nothing stays silent (honest, not faked).
   */
  private reportToolProtocolDrift(
    observedTools: readonly string[],
    runtime: ResolvedToolRuntime | null,
  ): void {
    if (!runtime) return;
    try {
      for (const record of observeToolProtocol(observedTools, runtime)) {
        if (record.protocol !== 'drift') continue;
        this.diag('tool.protocol_drift', { reasonCode: protocolDriftReasonCode(record) });
      }
    } catch {
      /* non-fatal: diagnostics must never break the event fan-out */
    }
  }

  /** Tracks whether we've already emitted the first-event transition
   *  for the current run — the spec only cares about the FIRST frame
   *  of each kind, not every subsequent one. */
  private firstRawEmitted = false;
  private firstSemanticEmitted = false;

  private maybeEmitFirstEvents(events: readonly LoopEvent[]): void {
    if (this.firstRawEmitted && this.firstSemanticEmitted) return;
    for (const e of events) {
      if (!this.firstRawEmitted && e.type !== 'session_start') {
        this.firstRawEmitted = true;
        const latency = this.startedAt > 0 ? Math.max(0, Date.now() - this.startedAt) : 0;
        this.diag('first.raw_event', { latencyMs: latency });
        if (this.firstSemanticEmitted) return;
      }
      if (
        !this.firstSemanticEmitted &&
        (e.type === 'text' || e.type === 'thinking' || e.type === 'tool_use' || e.type === 'api_stream')
      ) {
        this.firstSemanticEmitted = true;
        const latency = this.startedAt > 0 ? Math.max(0, Date.now() - this.startedAt) : 0;
        this.diag('first.semantic_event', { latencyMs: latency });
        if (this.firstRawEmitted) return;
      }
    }
  }

  async run(request: CodeRunRequest): Promise<void> {
    const now = Date.now();
    this.runId = `run-${this.conversationId}:${now.toString(36)}:${++runSeq}`;
    this.startedAt = now;
    this.busy = true;
    this.error = false;
    // First-event emission is per-run, not per-process. Reset here so
    // a second turn on the same warm CLI still gets a fresh latency
    // measurement.
    this.firstRawEmitted = false;
    this.firstSemanticEmitted = false;
    // Become visibly busy before Git baseline capture or runtime adoption.
    // Otherwise a slow additive step makes Send look like a no-op and leaves
    // the composer enabled for a second submission.
    this.bindingState = 'spawning';
    this.notify();
    // Conversation-scoped sink. The adopted (prewarmed) process
    // routes its output through this; it stays the same across
    // turns of one conversation (M4-A background write-back).
    this.turnSink = request.onEvents;

    // P2-1: build the result scope eagerly and establish the (bounded)
    // projection state BEFORE any prompt write (spec §7.2, audit P1-1).
    // The observer creates the run's event buffer synchronously; the Git
    // baseline itself completes asynchronously and never gates the run.
    this.lifecycleObserver = request.lifecycleObserver ?? null;
    const scope: RuntimeResultScope = {
      projectKey: this.projectKey,
      projectRoot: request.settings.cwd,
      conversationId: this.conversationId,
      mode: 'code',
      runId: this.runId!,
      turnId: request.turnId ?? '',
      startedAt: now,
    };
    this.resultScope = scope;
    await this.captureBaseline(scope);

    // Warm path: the same controller already owns a live idle CLI whose
    // ENTIRE runtime contract already matches this run (spec §9) — argv,
    // model, host, permission level, system prompt and Tool Profile.
    const fingerprint = runFingerprint(request);
    if (this.processId && this.ownedFingerprint === fingerprint) {
      this.bindingState = 'busy';
      this.notify();
      request.onRuntimeAcquired?.({ warm: true });
      const sent = await sendPromptToProcess(this.processId, request.prompt);
      if (sent) {
        this.diag('prompt.write.accepted');
        this.notify();
        return;
      }
      this.diag('prompt.write.rejected', { reasonCode: 'warm_reuse' });
      // The live handle rejected the write — it's dead. Detach it
      // and fall through to a fresh spawn.
      this.generation += 1;
      const rejectedId = this.processId;
      this.processId = null;
      this.pid = null;
      await stopTryloProcess(rejectedId).catch(() => { /* already gone */ });
    }

    // M4-C1 prewarm adoption: process_spawn returning means stdin is writable.
    // Do not wait for session_start here: the CLI can legitimately emit that
    // event only after it receives its first stream-json user message. Waiting
    // for the event before writing the message creates a permanent deadlock.
    // OS pipes buffer the prompt while the child finishes initialization.
    // A prewarm is adopted only by a run whose FULL runtime contract equals
    // the one the idle process was spawned with (spec §9). The old rule —
    // "argv is empty" — let a run adopt a process started with a different
    // model, host, permission level or system prompt, all of which are fixed
    // at spawn (spec §1.4). A Work run carrying a Tool Profile therefore
    // adopts only a Work prewarm of the same Profile.
    //
    // CONTEXT (2026-09-03): a prewarm is ALWAYS spawned EMPTY — no prompt and
    // no conversation history. Adopting it is therefore only safe for a run
    // that has nothing to replay (a genuinely fresh first message). A RESUMED
    // conversation carries `priorMessages`; reusing the empty idle CLI here
    // would hand the model only the current message, silently resetting the
    // thread to "first message". So history-bearing runs MUST skip adoption
    // and fall through to a cold spawn that replays `priorMessages` via
    // `promptWithHistory` (trylo-runner.ts).
    if (
      request.priorMessages.length === 0 &&
      !this.processId &&
      this.prewarmProcessId &&
      this.prewarmFingerprint === fingerprint
    ) {
      const adoptedId = this.prewarmProcessId;
      this.prewarmProcessId = null;
      this.prewarmReady = false;
      this.prewarmAttempt += 1;
      this.processId = adoptedId;
      this.ownedFingerprint = fingerprint;
      this.bindingState = 'busy';
      this.notify();
      request.onRuntimeAcquired?.({ warm: true });
      this.diag('prewarm.adopted');
      const sent = await sendPromptToProcess(adoptedId, request.prompt);
      if (sent) {
        this.diag('prompt.write.accepted');
        this.notify();
        return;
      }
      this.diag('prompt.write.rejected', { reasonCode: 'prewarm_adoption' });
      // Prewarm process rejected the write — it's dead. Detach
      // and fall through to a cold spawn.
      this.generation += 1;
      this.processId = null;
      this.pid = null;
      await stopTryloProcess(adoptedId).catch(() => { /* already gone */ });
    }

    // Cold path: (re)spawn for this conversation only. Detach any
    // prior process now that we are replacing it.
    // A live process whose runtime fingerprint differs from this run's — a
    // plain warm/prewarm CLI facing a run that needs a Tool Profile, a
    // different model, a different host, or a different permission level —
    // is stopped here so the cold spawn cannot leave an orphan behind
    // (spec §9: Profile / permission / model changes restart at the safety
    // boundary).
    if (this.processId) {
      const replacedId = this.processId;
      this.processId = null;
      this.pid = null;
      await stopTryloProcess(replacedId).catch(() => { /* already gone */ });
    }
    // Same for an un-adopted prewarm: once this run's contract differs, OR the
    // run must replay history (which the empty idle process never saw — see the
    // CONTEXT note above), the idle process can never be adopted — keeping it
    // would be exactly the process explosion §9 warns about (one active runtime
    // + one stale candidate per conversation, growing on every Profile flip).
    if (
      this.prewarmProcessId &&
      (this.prewarmFingerprint !== fingerprint || request.priorMessages.length > 0)
    ) {
      const stalePrewarmId = this.prewarmProcessId;
      this.prewarmProcessId = null;
      this.prewarmFingerprint = null;
      this.prewarmReady = false;
      this.prewarmAttempt += 1;
      await stopTryloProcess(stalePrewarmId).catch(() => { /* already gone */ });
    }
    this.generation += 1;
    request.onRuntimeAcquired?.({ warm: false });
    this.diag('cold.fallback');
    const spawnGeneration = this.generation;
    const guard = { isSuperseded: () => spawnGeneration !== this.generation };
    // PR-2 (§6.2): the classifier scope is snapshotted from THIS run's
    // request, exactly like the permission level — a mid-run picker change
    // must not re-classify an in-flight process's requests. An empty list
    // when no Profile was resolved means "nothing is managed by this run",
    // so an unexpected managed-looking frame routes to a human.
    const spawnToolRuntime = request.toolRuntime ?? null;
    const classifierScope = {
      projectRoot: request.settings.cwd,
      permissionLevel: request.permissionLevel,
      ...(spawnToolRuntime?.profileId ? { profileId: spawnToolRuntime.profileId } : {}),
      managedPackageIds: spawnToolRuntime
        ? spawnToolRuntime.packageHealth.filter((p) => p.available).map((p) => p.id)
        : [],
    };
    // PR-2: the CLI reports its tool list once per process (system/init →
    // loop_start). Observed per closure so a warm reuse never re-reports.
    let toolProtocolChecked = false;
    this.bindingState = 'spawning';
    this.notify();
    try {
      const { processId } = await startTrylo({
        prompt: request.prompt,
        cliPath: request.settings.cliPath,
        cwd: request.settings.cwd,
        apiKey: request.settings.apiKey,
        apiHost: request.settings.apiHost,
        apiModel: request.settings.apiModel,
        apiFormat: request.settings.apiFormat,
        apiKeyHeader: request.settings.apiKeyHeader,
        apiKeyPrefix: request.settings.apiKeyPrefix,
        extraHeadersText: request.settings.extraHeadersText,
        systemPrompt: request.settings.systemPrompt,
        codeMode: request.codeMode,
        // P2: the snapshotted level travels with the request, NOT
        // via a mutable global. A mid-run picker change cannot
        // reach this controller for the in-flight run.
        permissionLevel: request.permissionLevel,
        extraCliArgs: request.toolRuntime
          ? [...request.toolRuntime.cliArgs]
          : request.extraCliArgs,
        // §4.2: Profile env plus TRYLO_TEAM_SURFACE on Work, even when
        // the Profile failed — otherwise the child loads the Code roster.
        // teamMode (spawn_team on Code) adds TRYLO_TEAM_MODE.
        spawnEnv: effectiveSpawnEnv(request.surface, request.toolRuntime, request.teamMode),
        priorMessages: request.priorMessages,
        runId: this.runId,
        guard,
        projectKey: this.projectKey,
        conversationId: this.conversationId,
        onEvents: (events) => {
          if (spawnGeneration !== this.generation) return;
          if (!toolProtocolChecked) {
            const init = events.find((e) => e.type === 'loop_start');
            if (init && init.type === 'loop_start') {
              toolProtocolChecked = true;
              this.reportToolProtocolDrift(init.tools, spawnToolRuntime);
            }
          }
          const scope = this.resultScope;
          if (scope && this.lifecycleObserver) {
            try {
              this.lifecycleObserver.onEvents(scope, events);
            } catch {
              /* non-fatal: never let projection poison the event fan-out */
            }
          }
          this.maybeEmitFirstEvents(events);
          if (events.some((e) => e.type === 'loop_end' || e.type === 'session_end')) {
            this.busy = false;
            this.bindingState = 'idle';
            this.notify();
            if (scope) this.fireTerminal(scope, outcomeFromEvents(events));
          }
          request.onEvents(events);
        },
        onControlFrame: (frame) => {
          if (spawnGeneration !== this.generation) return;
          const processId = this.processId;
          if (!processId || !this.permissions) return;
          this.permissions.handleControlFrame(frame, {
            processId,
            projectKey: this.projectKey,
            conversationId: this.conversationId,
            ...classifierScope,
          });
        },
        onExit: (info) => {
          if (spawnGeneration !== this.generation) return;
          this.onChildExit(info);
        },
      });
      if (spawnGeneration !== this.generation) {
        // Superseded while spawning — stop the orphan we created.
        await stopTryloProcess(processId).catch(() => { /* already gone */ });
        return;
      }
      this.processId = processId;
      this.ownedFingerprint = fingerprint;
      this.bindingState = 'busy';
      this.notify();
      this.diag('cold.spawn');
    } catch (error) {
      if (spawnGeneration !== this.generation) return;
      this.processId = null;
      this.pid = null;
      this.bindingState = 'exited';
      this.error = true;
      this.busy = false;
      this.runId = null;
      this.notify();
      const reason = error instanceof Error ? error.message : 'unknown';
      this.diag('terminal', { reasonCode: `cold_spawn_failed:${reason.slice(0, 64)}` });
      this.fireTerminal(scope, 'failed');
      throw error;
    }
  }

  /** Send a correction into the current live turn without creating a second
   * controller run or resetting result attribution. The stream-json runtime
   * treats an additional user frame as steering at its next safe boundary. */
  async steer(prompt: string): Promise<boolean> {
    const processId = this.processId;
    if (!this.busy || !processId || this.bindingState !== 'busy') return false;
    const sent = await sendPromptToProcess(processId, prompt);
    this.diag(sent ? 'prompt.write.accepted' : 'prompt.write.rejected', {
      reasonCode: 'steering',
    });
    return sent;
  }

  /**
   * Stop one child task (Team seat) without killing the parent turn.
   * `taskId` is the CLI task id or the Agent tool_use_id (seat.id).
   */
  async stopTask(taskId: string): Promise<boolean> {
    const processId = this.processId;
    if (!processId || (this.bindingState !== 'busy' && this.bindingState !== 'ready')) {
      return false;
    }
    const sent = await sendControlLineToProcess(processId, buildStopTaskRequest(taskId));
    this.diag(sent ? 'prompt.write.accepted' : 'prompt.write.rejected', {
      reasonCode: 'stop_task',
    });
    return sent;
  }

  /**
   * M4-C1: spawn an idle CLI for this conversation, ahead of
   * the first user send, so the Node/CLI cold-start is paid before
   * the user submits. No prompt is written — no model request, no
   * history. `onReady` records the structured `session_start` signal;
   * adoption does not wait for it. Safe to re-call while a process or another
   * prewarm is already live. A prewarm failure is swallowed — the
   * next `run()` falls through to a normal cold spawn.
   *
   * `options.toolRuntime` makes the prewarm Profile-aware (spec §9): a Work
   * prewarm carries `work.core.v1` so the first Work message does not pay
   * MCP connect + cold start at once, and a Code prewarm is never adopted by
   * a Work run (or vice versa) because their fingerprints differ.
   */
  async prewarm(
    settings: SettingsForCodeRun,
    options: {
      readonly onReady?: () => void;
      readonly permissionLevel?: PermissionLevel;
      readonly toolRuntime?: ResolvedToolRuntime | null;
      readonly surface?: ToolSurface;
    } = {},
  ): Promise<void> {
    const onReady = options.onReady;
    if (this.processId || this.prewarmProcessId || this.prewarming) return;
    this.prewarming = true;
    this.prewarmReady = false;
    this.diag('prewarm.requested');
    const attempt = ++this.prewarmAttempt;
    let spawnedProcessId: string | null = null;
    // The idle process is spawned with THIS contract; only a run with the
    // same fingerprint may adopt it (spec §9).
    const runtime = options.toolRuntime ?? null;
    const spawnEnv = effectiveSpawnEnv(options.surface, runtime);
    const prewarmFingerprint = fingerprintForRun({
      cliPath: settings.cliPath,
      cwd: settings.cwd,
      apiKey: settings.apiKey,
      apiHost: settings.apiHost,
      apiModel: settings.apiModel,
      apiFormat: settings.apiFormat,
      apiKeyHeader: settings.apiKeyHeader,
      apiKeyPrefix: settings.apiKeyPrefix,
      extraHeadersText: settings.extraHeadersText,
      systemPrompt: settings.systemPrompt,
      permissionLevel: options.permissionLevel ?? 'workspace_write',
      extraCliArgs: runtime ? [...runtime.cliArgs] : [],
      toolRuntime: runtime,
      spawnEnv,
    });
    try {
      // PR-2: same classifier-scope snapshot as a real run, from the
      // prewarm's OWN contract (§9: adoption is an exact fingerprint match,
      // so the scope the closure carries matches the adopting run).
      const prewarmToolRuntime = runtime;
      const prewarmClassifierScope = {
        projectRoot: settings.cwd,
        permissionLevel: options.permissionLevel ?? 'workspace_write',
        ...(prewarmToolRuntime?.profileId ? { profileId: prewarmToolRuntime.profileId } : {}),
        managedPackageIds: prewarmToolRuntime
          ? prewarmToolRuntime.packageHealth.filter((p) => p.available).map((p) => p.id)
          : [],
      };
      let toolProtocolChecked = false;
      const { processId } = await startTryloPrewarm({
        cliPath: settings.cliPath,
        cwd: settings.cwd,
        apiKey: settings.apiKey,
        apiHost: settings.apiHost,
        apiModel: settings.apiModel,
        apiFormat: settings.apiFormat,
        apiKeyHeader: settings.apiKeyHeader,
        apiKeyPrefix: settings.apiKeyPrefix,
        extraHeadersText: settings.extraHeadersText,
        systemPrompt: settings.systemPrompt,
        codeMode: 'agent',
        permissionLevel: options.permissionLevel ?? 'workspace_write',
        extraCliArgs: runtime ? [...runtime.cliArgs] : undefined,
        spawnEnv,
        projectKey: this.projectKey,
        conversationId: this.conversationId,
        runId: `prewarm-${this.conversationId}`,
        onReady: () => {
          if (attempt !== this.prewarmAttempt) return;
          this.prewarmReady = true;
          onReady?.();
          this.notify();
        },
        onEvents: (events) => {
          // PR-2: observe the tool list the idle CLI reports at init, even
          // before a turn adopts this process — the init frame arrives once
          // per process and would otherwise be dropped here.
          if (!toolProtocolChecked) {
            const init = events.find((e) => e.type === 'loop_start');
            if (init && init.type === 'loop_start') {
              toolProtocolChecked = true;
              this.reportToolProtocolDrift(init.tools, prewarmToolRuntime);
            }
          }
          // Route output only once this process has been adopted as
          // the current owned process. Idle prewarm frames (ready
          // / nothing) are dropped.
          if (spawnedProcessId && this.processId === spawnedProcessId) {
            this.handleTurnEvents(events);
          }
        },
        onControlFrame: (frame) => {
          if (!spawnedProcessId || !this.permissions) return;
          if (this.processId !== spawnedProcessId && this.prewarmProcessId !== spawnedProcessId) return;
          this.permissions.handleControlFrame(frame, {
            processId: spawnedProcessId,
            projectKey: this.projectKey,
            conversationId: this.conversationId,
            ...prewarmClassifierScope,
          });
        },
        onExit: (info) => {
          if (spawnedProcessId && this.processId === spawnedProcessId) {
            this.onChildExit(info);
          } else if (spawnedProcessId && this.prewarmProcessId === spawnedProcessId) {
            // Prewarm died before being adopted — drop the idle
            // runtime; the next turn cold-spawns.
            this.prewarmProcessId = null;
            this.prewarmFingerprint = null;
            this.prewarmReady = false;
            this.notify();
          }
        },
      });
      spawnedProcessId = processId;
      this.diag('prewarm.spawned');
      // A user run may have started while process_spawn was in flight. Never
      // publish that late prewarm beside the real runtime; stop the orphan.
      if (attempt !== this.prewarmAttempt || this.busy || this.processId) {
        this.diag('prewarm.late_discarded', { reasonCode: 'superseded' });
        await stopTryloProcess(processId).catch(() => { /* already gone */ });
        return;
      }
      this.prewarmProcessId = processId;
      this.prewarmFingerprint = prewarmFingerprint;
      this.prewarmSpawnedAt = Date.now();
    } catch {
      // Prewarm failed; treat as unready so the next run cold-spawns.
      this.prewarmProcessId = null;
      this.prewarmFingerprint = null;
      this.prewarmReady = false;
      this.diag('prewarm.late_discarded', { reasonCode: 'spawn_failed' });
    } finally {
      this.prewarming = false;
    }
  }

  /** True while an idle prewarm is in flight or ready (for the
   *  Activity Center / status). */
  hasPrewarm(): { processId: string | null; ready: boolean } {
    return { processId: this.prewarmProcessId, ready: this.prewarmReady };
  }

  /** Forward turn output from an adopted prewarm process, mirroring
   *  the cold-spawn onOutput (loop_end → idle + forward). */
  private handleTurnEvents(events: readonly LoopEvent[]): void {
    const scope = this.resultScope;
    if (scope && this.lifecycleObserver) {
      try {
        this.lifecycleObserver.onEvents(scope, events);
      } catch {
        /* non-fatal */
      }
    }
    this.maybeEmitFirstEvents(events);
    if (events.some((e) => e.type === 'loop_end' || e.type === 'session_end')) {
      this.busy = false;
      this.bindingState = 'idle';
      this.lastIdleAt = Date.now();
      this.notify();
      if (scope) this.fireTerminal(scope, outcomeFromEvents(events));
    }
    const sink = this.turnSink;
    if (sink) sink(events);
  }

  /** P2-1 (spec §7.2): fire the exactly-once terminal notification for the
   *  active result scope. Clears the scope so a duplicate loop_end /
   *  session_end / exit / stop cannot re-finalize or re-save. */
  private fireTerminal(scope: RuntimeResultScope, outcome: CodeRunOutcome): void {
    if (this.resultScope !== scope) return;
    this.resultScope = null;
    this.diag('terminal', { reasonCode: outcome });
    const observer = this.lifecycleObserver;
    if (!observer) return;
    Promise.resolve(observer.onRunTerminal(scope, outcome)).catch(() => {
      /* non-fatal */
    });
  }

  /**
   * M4-C1 idle reclaim (spec §5.5 / §7.1): end THIS controller's
   * runtime if it has been idle >= `ttlMs`. Never touches a busy /
   * spawning runtime. Two cases:
   *   - an UN-ADOPTED prewarm (spawned but no turn adopted it yet);
   *   - an ADOPTED idle CLI sitting after loop_end.
   * Returns true when a runtime was reclaimed. The reaper only ever
   * calls this — busy runtimes are never reclaimed.
   */
  async reapIdleRuntime(ttlMs: number, now = Date.now()): Promise<boolean> {
    if (
      this.busy ||
      this.bindingState === 'busy' ||
      this.bindingState === 'spawning'
    ) {
      return false;
    }
    if (this.prewarmProcessId) {
      if (now - this.prewarmSpawnedAt < ttlMs) return false;
      const pid = this.prewarmProcessId;
      this.prewarmProcessId = null;
      this.prewarmFingerprint = null;
      this.prewarmReady = false;
      this.prewarmSpawnedAt = 0;
      this.prewarmAttempt += 1;
      await stopTryloProcess(pid).catch(() => { /* already gone */ });
      this.notify();
      return true;
    }
    if (this.processId && this.bindingState === 'idle') {
      if (now - this.lastIdleAt < ttlMs) return false;
      await this.stop();
      return true;
    }
    return false;
  }

  /** Stop THIS conversation's run and terminate its CLI. */
  async stop(): Promise<void> {
    // P2-1: a user-driven cancel is a terminal event for result projection.
    this.fireTerminalForActive('cancelled');
    this.generation += 1; // detach any in-flight spawn / process
    this.busy = false;
    this.turnSink = null;
    this.prewarmProcessId = null;
    this.prewarmFingerprint = null;
    this.prewarmReady = false;
    this.prewarmAttempt += 1;
    const processId = this.processId;
    this.processId = null;
    this.ownedFingerprint = null;
    this.pid = null;
    this.bindingState = 'exited';
    this.runId = null;
    this.error = false;
    if (processId) this.permissions?.clearProcess(processId);
    this.notify();
    if (processId) {
      await stopTryloProcess(processId).catch((err: unknown) => {
        // The Rust reaper still emits process.exited; a failed stop
        // command (already-dead child) is non-fatal.
        // eslint-disable-next-line no-console
        console.warn('[CodeRunController] stop failed', err);
      });
    }
  }

  /** Tear down this controller's handles without stopping the
   *  child process (workspace close / conversation delete). */
  dispose(): void {
    // P2-1: a disposed mid-run conversation must not stay `collecting`
    // forever — cancel its projection (spec §6.5). No-op when already final.
    this.fireTerminalForActive('cancelled');
    this.generation += 1;
    this.busy = false;
    this.turnSink = null;
    this.prewarmProcessId = null;
    this.prewarmFingerprint = null;
    this.prewarmReady = false;
    this.prewarmAttempt += 1;
    this.processId = null;
    this.ownedFingerprint = null;
    this.pid = null;
    this.bindingState = 'exited';
    this.runId = null;
  }

  private onChildExit(info: ProcessExitInfo): void {
    // Process exit always lands here, both for cold spawns and for
    // prewarms that have been adopted. We log it (no prompt text,
    // no signal name) so the diagnostic chain is complete.
    this.diag('process.exit', {
      ...(info.code !== null ? { exitCode: info.code } : {}),
      ...(info.signal !== null ? { signal: info.signal } : {}),
    });
    const crashedWhileBusy = this.busy && this.bindingState !== 'idle';
    // P2-1: a process that died on its own is a terminal outcome; if it was
    // already final (idle after loop_end) the guard makes this a no-op.
    this.fireTerminalForActive('exited');
    this.generation += 1;
    const deadProcessId = this.processId;
    this.processId = null;
    this.ownedFingerprint = null;
    this.pid = null;
    this.bindingState = 'exited';
    this.runId = null;
    this.busy = false;
    if (deadProcessId) this.permissions?.clearProcess(deadProcessId);
    if (crashedWhileBusy) {
      this.error = true;
    }
    this.notify();
  }

  private fireTerminalForActive(outcome: CodeRunOutcome): void {
    if (this.resultScope) {
      this.fireTerminal(this.resultScope, outcome);
    }
  }

  /** P2-1 (spec §7.2, audit P1-1): establish the Run-start projection state
   *  with a bounded budget. On timeout or error we proceed anyway — result
   *  projection is additive, never a gate on the Agent run. */
  private async captureBaseline(scope: RuntimeResultScope): Promise<void> {
    const observer = this.lifecycleObserver;
    if (!observer) return;
    try {
      await Promise.race([
        Promise.resolve(observer.onRunStarted(scope)),
        new Promise<void>((resolve) => {
          setTimeout(resolve, BASELINE_TIMEOUT_MS);
        }),
      ]);
    } catch {
      /* non-fatal: a failed baseline degrades the projection, not the run */
    }
  }

  private notify(): void {
    this.onChange();
  }
}

/** Map a terminal batch of loop events to a result outcome (spec §7.2).
 *  Assistant text is never used — only the structured event fields. */
function outcomeFromEvents(events: readonly LoopEvent[]): CodeRunOutcome {
  for (const e of events) {
    if (e.type === 'session_end') {
      if (e.reason === 'abort') return 'cancelled';
      if (e.reason === 'error') return 'failed';
      return 'completed';
    }
    if (e.type === 'loop_end') {
      return e.isError ? 'failed' : 'completed';
    }
    if (e.type === 'aborted') return 'cancelled';
  }
  return 'completed';
}
